### ISSUE TITLE
Question: how to use custom annotations, like enhancers?

### ISSUE THREAD

**Issue by Rseq** [ComputationalRegulatoryGenomicsICL/GenomicInteractions#1]
Hi, 

First of all, many thanks for making this package available.
I have been trying to use `annotateInteractions` with custom annotations like enhancers (.bed format) without success.
I saw that it is somehow possible to use custom annotations, like in the paper that was used an enhancer annotation (https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-015-2140-x/figures/3).
However, there are no details on how to use custom annotations in the vignette http://bioconductor.org/packages/release/bioc/vignettes/GenomicInteractions/inst/doc/chiapet_vignette.html

I have tried using `makeTxDb` but it doesn't work.

Is there any easy way to do it?

Thank you for your time.

**Comment by liz-is** [comment]
Hi,

There is an example of annotation using enhancers (in GRanges format) in the other vignette: http://bioconductor.org/packages/release/bioc/vignettes/GenomicInteractions/inst/doc/hic_vignette.html Does this help? If you can read in enhancers from a .bed file and convert to GRanges format, that should work fine.

If that doesn't help, please provide some example code for what you've tried so far and I'll see if I can help.

Thanks for your interest in the package!

**Comment by Rseq** [comment]
Hi, 
Many thanks for your prompt reply!
I did not notice that the info I wanted was on the second vignette.
It worked out quite nicely!

Many thanks!
