### ISSUE TITLE
viewPoint error message?

### ISSUE THREAD

**Issue by jaclyn-marie** [ComputationalRegulatoryGenomicsICL/GenomicInteractions#14]
Hi Genomic Interactions team, 

I am trying to generate some v4C plots, and I am having issues with viewPoint(). I import my GI object, generate the anchor/bait, and region. However when I try to generate the viewPoint I get this error:

`Error in .local(query, subject, maxgap, minoverlap, type, select, ...) : 
  unused argument (use.region = "first")`

I would be grateful for any insight or tips you can share!

Thanks!
Jaclyn

**Comment by liz-is** [comment]
Hi Jaclyn,

I can't reproduce this with the example in the documentation for the viewPoint function. Could you please see if this works for you?

```
library(GenomicInteractions)
data(hic_example_data)
library(GenomicRanges)
pos <- GRanges(seqnames='chr15', ranges=IRanges(start=59477709, end=59482708))
region <- GRanges(seqnames='chr15', ranges=IRanges(start=58980209, end=59980208))
vp <- viewPoint(hic_example_data, pos, region)
```

Also, what version of GenomicInteractions are you using?

**Comment by jaclyn-marie** [comment]
Hi @liz-is,

The example code works for viewPoint, After inspecting the objects from your test data versus mine, I realized my error. I imported my bedpe file as a GRanges object and did not convert it to a GInterations obejct. Can you please advise me the swiftest way to change my data to a GInteractions object? From the online tutorial it looks as if I would have to break this down into two and then recombine them, or could I subset the GRanges object twice by columns?

I am using GenomicInteractions 1.28.0
Thank you for any tips you can provide!

Sincerely,
Jaclyn 

**This is how I imported my psuedo-bedpe file:**

``df1 <- as.data.frame(read.table(bedpe1, header = TRUE, sep="\t", stringsAsFactors=FALSE))``
``dmso <- makeGRangesFromDataFrame(df1,
                                 keep.extra.columns=TRUE,
                                 ignore.strand = TRUE,
                                 seqnames.field="chrI",
                                 start.field="startI"
                                 end.field="endJ",
                                 starts.in.df.are.0based=FALSE)``

>head(dmso)
GRanges object with 6 ranges and 9 metadata columns:
      seqnames          ranges strand |      endI        chrJ    startJ         D    counts    pvalue    qvalue         mu      sdev
         <Rle>       <IRanges>  <Rle> | <integer> <character> <integer> <integer> <integer> <numeric> <numeric>  <numeric> <numeric>
  [1]     chr3 2170000-2845000      * |   2175000        chr3   2840000    670000         7  2.60e-13  5.57e-09 0.00618358 0.0795732
  [2]     chr3 4295000-4815000      * |   4300000        chr3   4810000    515000         6  8.28e-11  1.10e-06 0.00855021 0.0939881
  [3]     chr3 4250000-4920000      * |   4255000        chr3   4915000    665000       120 9.30e-195 6.39e-189 0.00664925 0.0825878
  [4]     chr3 4740000-5025000      * |   4745000        chr3   5020000    280000        10  3.58e-13  7.38e-09 0.02128184 0.1517847
  [5]     chr3 4750000-5025000      * |   4755000        chr3   5020000    270000         8  1.95e-10  2.31e-06 0.02432212 0.1631462
  [6]     chr3 4975000-5025000      * |   4980000        chr3   5020000     45000        95  2.26e-19  1.03e-14 0.50645856 1.2253041

**Comment by liz-is** [comment]
Ah, I see! You can make two GRanges for the two anchors of each interaction, and use these to construct a GInteractions object, like so:

```
dmso_anchor1 <- makeGRangesFromDataFrame(df1,  ignore.strand = TRUE, 
    seqnames.field="chrI", start.field="startI" end.field="endI", starts.in.df.are.0based=FALSE)
dmso_anchor2 <- makeGRangesFromDataFrame(df1,  ignore.strand = TRUE, 
    seqnames.field="chrJ", start.field="startJ" end.field="endJ", starts.in.df.are.0based=FALSE)
gi <- GInteractions(dmso_anchor1, dmso_anchor2)
mcols(gi) <- df1
```

**Comment by jaclyn-marie** [comment]
Thank you SO much for your help @liz-is!
