### ISSUE TITLE
exporting bedpe with annotations

### ISSUE THREAD

**Issue by jaclyn-marie** [ComputationalRegulatoryGenomicsICL/GenomicInteractions#15]
Hi @liz-is, 

I would like to export my annotated ginteractions object as a bedpe with all columns of metadata (including the annotated anchors/regions)

gi object:
``df1 <- as.data.frame(read.table(bedpe1, header = TRUE, sep="\t", stringsAsFactors=FALSE))``

``g1 <- makeGRangesFromDataFrame(df1,  
                               ignore.strand = TRUE, seqnames.field="chr1", 
                               start.field="start1", end.field="end1", 
                               starts.in.df.are.0based=FALSE)``
``g2 <- makeGRangesFromDataFrame(df1,  
                               ignore.strand = TRUE, seqnames.field="chr2", 
                               start.field="start2", end.field="end2", 
                               starts.in.df.are.0based=FALSE)``
``giWT <- GInteractions(g1, g2)``
``mcols(giWT) <- df1``

gRanges object:
``bed1 <- as.data.frame(read.table(bedpath1, header = FALSE, col.names = c("chrom", "chromStart", "chromEnd", "name", "score", "dot", "signalValue", "pval", "qval", "peak"), sep="\t", stringsAsFactors=FALSE))``

``WTtf <- makeGRangesFromDataFrame(bed1,  
                                  ignore.strand = TRUE, seqnames.field="chrom", 
                                  start.field="chromStart", end.field="chromEnd", 
                                  keep.extra.columns = TRUE, 
                                  starts.in.df.are.0based=FALSE)``

annotated gi object:
``anno1 = list(tf=WTtf)``
``annotateInteractions(giWT, anno1, "name")``
``p.one1 = anchorOne(giWT)$node.class == "tf"``
``p.two1 = anchorTwo(giWT)$node.class == "tf"``
``giWT[p.one1|p.two1]``
``categoriseInteractions(giWT)``

Is there a way to export my bedpe file with all metadata I imported into my GI object, plus the annotation of "tf" anchors? It seems that ``export.bedpe()`` only exports minimal columns plus the "score". I appreciate any tips you are able to share!

Sincerely,
Jaclyn

**Comment by liz-is** [comment]
Hello,

The easiest way will be to use `as.data.frame(giWT)`. You can then select / reorder the columns you want and export using `write.table()`.  `export.bedpe` only exports columns which conform to the [BEDPE format definition](https://bedtools.readthedocs.io/en/latest/content/general-usage.html#bedpe-format).

**Comment by jaclyn-marie** [comment]
Thank you so much @liz-is ! Works like a gem
