### ISSUE TITLE
Question: How to subset interactions and transform it to dataframe?

### ISSUE THREAD

**Issue by Rseq** [ComputationalRegulatoryGenomicsICL/GenomicInteractions#2]
Hi,

I have another question which I could only find a partial answer in the vignattes. 
I want to use a third package to visualise my interactions in a certain locus. How I can subset a certain region of `annotateInteractions(SMC_GR, annotation.features)` that contains the chr-start-end and all interactions found in the annotation.features and transform it to data.frame?

Also, if I want to just subset a certain region, the best way is to use `viewPoint( )`, correct?
However, how can I do it if I want to specify the region by an annotation name instead of its coordinates and transform it to a data.frame?

I tried 
`SMC_GR@regions@elementMetadata@listData$promoter.id=="promoter-TSS (NM_148172)"`
But I can only extract the element and not its interactions...

Any help on this would be great as I could find a work around using GRanges functions neither.

Thank you for your time,

Best

**Comment by liz-is** [comment]
Hi,

I'm not sure I totally understand what your aim is. `findOverlaps(gi, my_promoter)` will give you a `GenomicInteractions` object that includes all interactions where one or both anchors overlap the region of interest. You can then convert this to a data frame using `as.data.frame`. This seems like a simpler way to achieve your goal, if I understand it correctly.

If that doesn't help, could you explain a bit more what you want to acheive?

**Comment by liz-is** [comment]
Hi @Rseq, were you able to solve your issue?

**Comment by liz-is** [comment]
Closing due to lack of information.

**Comment by Rseq** [comment]
Hi!
Sorry for my very late update. I could sort out!
Many thanks
