### ISSUE TITLE
Doesn't recognize bedpe file

### ISSUE THREAD

**Issue by mjko1210** [ComputationalRegulatoryGenomicsICL/GenomicInteractions#3]
Hi,
I want to use GenomicInteractions tool for representing SV arcs.

I have input tab delimited bedpe file (example.bedpe).

chrom1	start1	end1	chrom2	start2	end2	name	score	strand1	strand2
chr1	45620028	45620028	chr1	46408226	46408226	.	.	+	-
chr1	123260610	123260610	chr1	124502690	124502690	.	.	-	+
chr1	157075534	157075534	chr1	157192322	157192322	.	.	+	-

And then I ran following command
sv_data <- makeGenomicInteractionsFromFile('example.bedpe', type="bedpe")

However, it gives me an error as below:

Error in makeGenomicInteractionsFromFile("example.bedpe",  :
  bedpe file does not appear to be in the correct format. See http://bedtools.readthedocs.org/en/latest/content/general-usage.html for details

It's bedpe format but I'm not sure why it's complaining.

Your comments will be appreciated! Thanks!

MJ

**Comment by liz-is** [comment]
The import function currently requires that the "score" column (column 8) in a bedpe file is numeric. So as a workaround you can replace the "." with "0" and it'll work. Note that you can store any type of data in the columns after the strand columns. 

However, I re-read the bedpe definition and I see that bedtools allows any string to be stored in this column. That makes sense to me, so I'll go ahead and change this for the next release after checking it doesn't break anything in the package.

**Comment by mjko1210** [comment]
Thanks. This is working now but I had to remove first line (column names).

**Comment by liz-is** [comment]
I've updated the import function to use the BEDPE import function provided by the rtracklayer package. This will be available in the next release of Bioconductor (~ end of April), and available in the devel version within the next couple of days.
